import { ROLES } from './roles';

export const PERMISSIONS = {
  MANAGE_USERS: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  VIEW_PATIENTS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.DOCTOR, ROLES.STAFF],
  CREATE_PATIENTS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.STAFF],
  UPDATE_PATIENTS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.STAFF],
  ARCHIVE_PATIENTS: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  DELETE_PATIENTS: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  CREATE_VISITS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.DOCTOR, ROLES.STAFF],
  VIEW_VISITS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.DOCTOR, ROLES.STAFF],
  ADD_CLINICAL_RECORDS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.STAFF],
  VIEW_CLINICAL_RECORDS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.DOCTOR, ROLES.STAFF],
  ADD_LAB_RESULTS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.STAFF],
  VIEW_LAB_RESULTS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.DOCTOR, ROLES.STAFF],
  ADD_DIAGNOSIS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.DOCTOR],
  VIEW_DIAGNOSIS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.DOCTOR, ROLES.STAFF],
  MANAGE_FOLLOWUPS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.DOCTOR, ROLES.STAFF],
  VIEW_RESEARCH_DATA: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.RESEARCH_ADMIN],
  EXPORT_RESEARCH_DATA: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.RESEARCH_ADMIN],
  VIEW_AUDIT_LOGS: [ROLES.SUPER_ADMIN],
  MANAGE_SETTINGS: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
};
