const PERMISSIONS = {
  MANAGE_USERS: ['SUPER_ADMIN', 'ADMIN'],
  VIEW_PATIENTS: ['SUPER_ADMIN', 'ADMIN', 'DOCTOR', 'STAFF'],
  CREATE_PATIENTS: ['SUPER_ADMIN', 'ADMIN', 'STAFF'],
  UPDATE_PATIENTS: ['SUPER_ADMIN', 'ADMIN', 'STAFF'],
  ARCHIVE_PATIENTS: ['SUPER_ADMIN', 'ADMIN'],
  DELETE_PATIENTS: ['SUPER_ADMIN', 'ADMIN'],

  CREATE_VISITS: ['SUPER_ADMIN', 'ADMIN', 'DOCTOR', 'STAFF'],
  VIEW_VISITS: ['SUPER_ADMIN', 'ADMIN', 'DOCTOR', 'STAFF'],

  ADD_CLINICAL_RECORDS: ['SUPER_ADMIN', 'ADMIN', 'STAFF'],
  VIEW_CLINICAL_RECORDS: ['SUPER_ADMIN', 'ADMIN', 'DOCTOR', 'STAFF'],

  ADD_LAB_RESULTS: ['SUPER_ADMIN', 'ADMIN', 'STAFF'],
  VIEW_LAB_RESULTS: ['SUPER_ADMIN', 'ADMIN', 'DOCTOR', 'STAFF'],

  ADD_DIAGNOSIS: ['SUPER_ADMIN', 'ADMIN', 'DOCTOR'],
  VIEW_DIAGNOSIS: ['SUPER_ADMIN', 'ADMIN', 'DOCTOR', 'STAFF'],

  MANAGE_FOLLOWUPS: ['SUPER_ADMIN', 'ADMIN', 'DOCTOR', 'STAFF'],

  VIEW_RESEARCH_DATA: ['SUPER_ADMIN', 'ADMIN', 'RESEARCH_ADMIN'],
  EXPORT_RESEARCH_DATA: ['SUPER_ADMIN', 'ADMIN', 'RESEARCH_ADMIN'],

  VIEW_AUDIT_LOGS: ['SUPER_ADMIN'],
  MANAGE_SETTINGS: ['SUPER_ADMIN', 'ADMIN'],
};

module.exports = { PERMISSIONS };
